apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:hVnacrk=,iv:d6i9ctAa4bk2IdmSG7sjxYbLkRKlVRTORO1lwKka2tA=,tag:WWJjECk6qt7tjRL5feDSFA==,type:str]
    admin-password: ENC[AES256_GCM,data:btZqnZXcH1f3og==,iv:btKlxjYM7nh5ScOaXHm3JM61bqEM26LBBqEm6EOmM9k=,tag:R2wgCtyjWDKrqre0/730KQ==,type:str]
sops:
    age:
        - recipient: age1svhxh2aql567xg7d0h6wyxmypd36th6s63j70ft8c8w7w56mtp7sm6xjae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQzZiVkxDak1zWGp5YXpM
            NWQ1cndOYVRsSU90Y1U2OWxJSUdkb3lTdUhzClNGV1RPd3JHWlR2QXVkNGs2N1JZ
            YXpENVZtMjZjVUlkRFhqN2JIcVErMU0KLS0tIFhGdjkrK2xub0tJcklUTndVNG1T
            RmwyTTA5OTc0NS9haklDbGdqWnJBaXcKTDvmcf3JK2niW5Av07swqWbqzW8E9/mU
            4TtxC919wYyGfF2zgqOM9naTOx3cyg/1JHgJMn3HJqjTeP6wg1f27Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T10:53:17Z"
    mac: ENC[AES256_GCM,data:eMPswDwwDQhrPK1RfM7mHSz/WT73utK07xTkn/48NO5rMKlUOCBr36O0MjwDPqDzLbHnh2gNUHeNFG9MDrS9jdJYeH1GAXOvZzJgxivvINEMKyE5nKCAkfBeAr3e9bsFnch9kwg5ZPT1FaRqsiLaSysQvRHHgUpJpB/QYE8SnOA=,iv:aGFsg5L4P/6SC14KrsvL/cwrkEAMMvLPcAXuyIYYnz4=,tag:kp3CMJMQ5XYeR49G+PwwCg==,type:str]
    encrypted_regex: ^(data|stringData|secrets|password|token|key)$
    version: 3.11.0
